### ISSUE TITLE
Translator return funny character for the entire line

### ISSUE THREAD

**Issue by minhanh1234** [dingedi/argos-translate-files#11]
I try to translate the following txt file from ru to en

2022-03-19	13:34:33	God	буквально час два и все будет у вас)
2022-03-19	13:34:41	fdsfgs	да, я видел :)

and i am getting the following results.

♪
♪

or sometime i would get 

_
_

Would anyone know why i am getting the following result?
Thanks

**Comment by dingedi** [comment]
This comes from models that sometimes make mistakes.
You can open an issue here it will be better:
[https://github.com/argosopentech/argos-translate](https://github.com/argosopentech/argos-translate)
